version: 2

jobs:
  build:
    docker:
      - image: nixos/nix
    working_directory: ~/rules_haskell
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apk --no-progress update
            apk --no-progress add bash ca-certificates
            nix-channel --update
            nix-env -iA nixpkgs.bazel nixpkgs.binutils nixpkgs.python
      - run:
          name: Build
          command: bazel build --jobs=2 //...
      - run:
          name: Run tests
          command: bazel test //... --config=ci
      - run:
          name: Test REPL for libraries
          command: bazel-bin/tests/haskell_repl/haskell_lib_repl -e ":quit"
      - run:
          name: Test REPL for binaries
          command: bazel-bin/tests/haskell_repl/haskell_bin_repl -e ":quit"
      - run:
          name: Test start script
          command: |
            pwd=$(pwd)
            cd $(mktemp -d)
            $pwd/start
            bazel fetch //... --config=ci
